-- Seed data: SF Rec & Park tennis facility directory
-- Source: https://www.sfrecpark.org/1446/Tennis-Court-Directory (fetched 2026-08-29)
-- Re-run is safe: upserts on the unique slug.
--
-- Goldman Tennis Center is booked through a separate external system
-- (LifetimeActivities), so it's marked crowd_reportable = false; add its
-- booking URL to reservation_url by hand once you have it.

insert into locations (slug, name, zip, num_reservable, num_walkup, lights, restrooms, crowd_reportable) values
  ('alamo-square', 'Alamo Square', '94117', 0, 1, false, true, true),
  ('alice-chalmers', 'Alice Chalmers', '94112', 0, 1, false, true, true),
  ('alice-marble', 'Alice Marble', '94109', 4, 0, false, false, true),
  ('alta-plaza', 'Alta Plaza', '94115', 0, 3, false, false, true),
  ('aptos', 'Aptos', '94127', 0, 1, false, false, true),
  ('argonne', 'Argonne', '94121', 0, 1, false, true, true),
  ('balboa-park', 'Balboa Park', '94112', 4, 0, false, true, true),
  ('buena-vista', 'Buena Vista', '94117', 1, 1, false, false, true),
  ('cabrillo', 'Cabrillo', '94121', 0, 1, false, true, true),
  ('cayuga', 'Cayuga', '94112', 0, 1, true, true, true),
  ('coronado', 'Coronado', '94110', 0, 1, true, true, true),
  ('crocker-amazon', 'Crocker Amazon', '94112', 3, 0, true, true, true),
  ('dolores-park', 'Dolores Park', '94114', 3, 3, true, true, true),
  ('douglass', 'Douglass', '94114', 0, 1, false, true, true),
  ('dupont', 'DuPont', '94121', 4, 0, false, false, true),
  ('eureka-valley', 'Eureka Valley', '94114', 0, 1, false, true, true),
  ('excelsior', 'Excelsior', '94112', 0, 1, true, true, true),
  ('fulton', 'Fulton', '94121', 1, 0, false, true, true),
  ('george-christopher', 'George Christopher', '94131', 0, 1, true, true, true),
  ('glen-canyon', 'Glen Canyon', '94127', 1, 1, true, true, true),
  ('golden-gate-heights', 'Golden Gate Heights', '94116', 0, 2, false, false, true),
  ('goldman-tennis-center', 'Goldman Tennis Center', '94122', 16, 0, true, true, false),
  ('grattan', 'Grattan', '94117', 0, 1, false, true, true),
  ('hamilton', 'Hamilton', '94115', 2, 0, true, true, true),
  ('hayes-valley', 'Hayes Valley', '94102', 0, 1, true, true, true),
  ('helen-wills', 'Helen Wills', '94109', 1, 0, false, true, true),
  ('holly-park', 'Holly Park', '94110', 0, 1, false, true, true),
  ('jp-murphy', 'J.P. Murphy', '94116', 3, 0, false, true, true),
  ('jackson', 'Jackson', '94107', 1, 0, true, false, true),
  ('james-rolph-jr', 'James Rolph Jr.', '94110', 0, 2, true, true, true),
  ('joe-dimaggio', 'Joe DiMaggio', '94113', 1, 2, true, true, true),
  ('junipero-serra', 'Junipero Serra', '94118', 0, 1, false, false, true),
  ('lafayette', 'Lafayette', '94132', 2, 0, false, true, true),
  ('laurel-hill', 'Laurel Hill', '94132', 0, 1, false, true, true),
  ('margaret-s-hayward', 'Margaret S. Hayward', '94102', 0, 2, true, true, true),
  ('mccoppin-square', 'McCoppin Square', '94116', 0, 1, false, true, true),
  ('mclaren', 'McLaren', '94134', 6, 0, false, true, true),
  ('merced-heights', 'Merced Heights', '94132', 0, 2, true, true, true),
  ('minnie-lovie-ward', 'Minnie & Lovie Ward', '94131', 2, 0, false, true, true),
  ('miraloma', 'Miraloma', '94112', 1, 0, false, true, true),
  ('mission', 'Mission', '94127', 0, 2, true, true, true),
  ('mission-creek-park', 'Mission Creek Park', '94107', 0, 1, true, true, true),
  ('moscone', 'Moscone', '94113', 4, 0, true, true, true),
  ('mountain-lake', 'Mountain Lake', '94123', 4, 0, false, true, true),
  ('noe-valley', 'Noe Valley', '94114', 0, 1, false, false, true),
  ('palega', 'Palega', '94118', 0, 2, true, true, true),
  ('parkside-square', 'Parkside Square', '94132', 4, 0, false, true, true),
  ('peixotto-15th-st', 'Peixotto (15th St)', '94102', 0, 2, false, false, true),
  ('potrero-hill', 'Potrero Hill', '94110', 2, 0, true, true, true),
  ('presidio-wall', 'Presidio Wall', '94118', 4, 0, false, true, true),
  ('richmond', 'Richmond', '94121', 1, 0, false, true, true),
  ('rochambeau', 'Rochambeau', '94121', 0, 1, false, true, true),
  ('rossi', 'Rossi', '94110', 3, 0, false, true, true),
  ('silver-terrace', 'Silver Terrace', '94124', 0, 1, true, true, true),
  ('south-sunset', 'South Sunset', '94116', 0, 1, false, true, true),
  ('st-marys', 'St. Mary''s', '94110', 2, 0, false, true, true),
  ('states-street-flint-st', 'States Street (Flint St)', '94114', 0, 2, false, false, true),
  ('stern-grove', 'Stern Grove', '94132', 2, 0, false, true, true),
  ('sunnyside', 'Sunnyside', '94127', 0, 1, false, true, true),
  ('sunset-rec', 'Sunset Rec', '94122', 2, 0, false, true, true),
  ('upper-noe', 'Upper Noe', '94131', 1, 0, true, true, true),
  ('west-portal', 'West Portal', '94127', 0, 1, false, true, true),
  ('west-sunset', 'West Sunset', '94116', 0, 2, true, true, true),
  ('youngblood-coleman', 'Youngblood Coleman', '94124', 0, 2, true, true, true)
on conflict (slug) do update set
  name = excluded.name,
  zip = excluded.zip,
  num_reservable = excluded.num_reservable,
  num_walkup = excluded.num_walkup,
  lights = excluded.lights,
  restrooms = excluded.restrooms,
  crowd_reportable = excluded.crowd_reportable;
